language: c
script: asdf plugin-test java $TRAVIS_BUILD_DIR 'java -version' --asdf-tool-version 'adoptopenjdk-11.0.3'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
